Repository khojiakbar63/ChipDipReactTS, pull requests merged in 2024-10, with the labels that each got.

#3 Dev 2
  package-lock.json
  package.json
  src/assets/Img/CaruselImg_1.png
  src/assets/Img/CaruselImg_2.png
  src/assets/Img/HeroImg.png
  src/assets/Img/autoparts.png
  src/assets/Img/chemicals.png
  src/assets/Img/connectors.png
  src/assets/Img/oscilloscopes.png
  src/assets/Img/protect.png
  src/assets/Img/relay.png
  src/assets/Img/zapchasti.png
  src/components/sections/home/application/_style.scss
  src/components/sections/home/application/index.tsx
  src/components/sections/home/hero/_style.scss
  src/components/sections/home/hero/index.tsx
  src/components/sections/home/pop-categories/_style.scss
  src/components/sections/home/pop-categories/index.tsx
Labels: enhancement

#5 Home Bestsellers => dev-3
  package-lock.json
  package.json
  src/assets/images/diot.png
  src/assets/images/kitay.png
  src/assets/images/linoya.png
  src/assets/images/mastech.png
  src/assets/images/navigator.png
  src/assets/images/proskit.png
  src/assets/images/robiton.png
  src/assets/images/skz.png
  src/assets/images/soeks.png
  src/assets/images/testo.png
  src/assets/images/turbojet.png
  src/assets/images/znatok.png
  src/components/sections/home/04-bestsellers/_style.scss
  src/components/sections/home/05-best-offers/_style.scss
  src/components/sections/home/06-gaining-popularity/_style.scss
  src/components/sections/home/best-offers/_style.scss
  src/components/sections/home/best-offers/index.tsx
  src/components/sections/home/bestsellers/_style.scss
  src/components/sections/home/bestsellers/index.tsx
  src/components/sections/home/gaining-popularity/_style.scss
  src/components/sections/home/gaining-popularity/index.tsx
  src/mocks/index.tsx
Labels: duplicate

#8 cards updates
  src/assets/images/line.svg
  src/components/sections/home/best-offers/_style.scss
  src/components/sections/home/best-offers/index.tsx
  src/components/sections/home/bestsellers/_style.scss
  src/components/sections/home/bestsellers/index.tsx
  src/components/sections/home/gaining-popularity/_style.scss
  src/components/sections/home/gaining-popularity/index.tsx
Labels: duplicate

#10 added videos and news
  index.html
  package-lock.json
  src/components/index.tsx
  src/components/sections/home/news-videos/_style.scss
  src/components/sections/home/news-videos/index.tsx
  src/components/sections/home/news-videos/mock/mock.js
  src/components/sections/home/news-videos/news/_style.scss
  src/components/sections/home/news-videos/news/index.tsx
  src/components/sections/home/news-videos/video/_style.scss
  src/components/sections/home/news-videos/video/index.tsx
  src/components/sections/home/news/_style.scss
  src/components/sections/home/news/index.tsx
  src/components/sections/home/video/_style.scss
  src/components/sections/home/video/index.tsx
  src/pages/home/index.tsx
Labels: wontfix

#11 Dev 2
  src/assets/Img/CaruselImg_1.png
  src/assets/Img/CaruselImg_3.png
  src/assets/Img/CaruselImg_4.png
  src/assets/Img/CaruselImg_5.png
  src/components/sections/home/application/_style.scss
  src/components/sections/home/application/index.tsx
  src/components/sections/home/hero/_style.scss
  src/components/sections/home/hero/index.tsx
  src/components/sections/home/pop-categories/_style.scss
  src/components/sections/home/pop-categories/index.tsx
  src/components/ui/Carusel/index.tsx
  src/components/ui/Carusel/style.scss
  src/mocks/index.tsx
Labels: enhancement

#12 recomended
  src/components/sections/home/pop-categories/_style.scss
Labels: enhancement

#13 Consumables ConsumablesConsumables dev-2
  src/assets/Img/ximya.jpg
  src/assets/Img/Виниловая.jpg
  src/assets/Img/Кембрик.jpg
  src/assets/Img/Клейкая.jpg
  src/assets/Img/Краски.jpg
  src/assets/Img/Лабораторное.jpg
  src/assets/Img/Макетные.jpg
  src/assets/Img/Маркировка.jpg
  src/assets/Img/Материалы.jpg
  src/assets/Img/Оргстекло.jpg
  src/assets/Img/Тара.jpg
  src/assets/Img/Теплопроводящие.jpg
  src/assets/Img/Термоусадочная.jpg
  src/assets/Img/конструирования.jpg
  src/components/sections/consumables/consumables-description/_style.scss
  src/components/sections/consumables/consumables-description/index.tsx
  src/components/sections/consumables/consumables/_style.scss
  src/components/sections/consumables/consumables/index.tsx
  src/mocks/index.tsx
Labels: enhancement

#15 Dev 2
  src/components/sections/consumables/consumables-description/_style.scss
Labels: enhancement
